### ISSUE TITLE
Error on logout()

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-JSClient#3]
Receiving this error on logout() using Node.js v10.16.3

```
{ Error: Value is not a string.
    at /Users/js/Documents/Aktuelle Projekte/Openframe/Repos/Openframe-ArtworkAvailabilityChecker/node_modules/openframe-jsclient/dist/of.js:698:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   Body {
     url: 'https://api.openframe.io/v0/users/logout',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { _headers: [Object] },
     ok: false,
     body:
      PassThrough {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: true,
     size: 0,
     timeout: 0,
     _raw:
      [ <Buffer 7b 22 65 72 72 6f 72 22 3a 7b 22 73 74 61 74 75 73 43 6f 64 65 22 3a 34 30 30 2c 22 6e 61 6d 65 22 3a 22 45 72 72 6f 72 22 2c 22 6d 65 73 73 61 67 65 ... > ],
     _abort: false,
     _bytes: 78 } }
```

**Comment by jmwohl** [comment]
Fixed in the latest release.
